/**************************************************************************************************\
 *** 
 *** Simulink model       : test
 *** TargetLink subsystem : test/power_window_controller_ver3
 *** Codefile             : power_window_controller_ver3.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2025-02-19 01:23:33
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            power_window_controller_ver3
 *** Sa2            power_window_controller_ver3/detect_obstacle_endstop
 *** Sa3            power_window_controller_ver3/validate_driver
 *** Sa4            power_window_controller_ver3/validate_passenger
 *** Sa5            power_window_controller_ver3/detect_obstacle_endstop/detect_endstop
 *** Sa6            power_window_controller_ver3/detect_obstacle_endstop/detect_obstacle
 *** Sa7            power_window_controller_ver3/validate_driver/check_down
 *** Sa8            power_window_controller_ver3/validate_driver/check_up
 *** Sa9            power_window_controller_ver3/validate_driver/driver_switch
 *** Sa10           power_window_controller_ver3/validate_driver/mutually_exclusive
 *** Sa11           power_window_controller_ver3/validate_passenger/check_down
 *** Sa12           power_window_controller_ver3/validate_passenger/check_up
 *** Sa13           power_window_controller_ver3/validate_passenger/mutually_exclusive
 *** Sa14           power_window_controller_ver3/validate_passenger/passenger_switch
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** Ca0            test                                            
 *** Ca1            power_window_controller_ver3/control            
 *** Ca2            power_window_controller_ver3/control.safe       
 *** Ca3            power_window_controller_ver3/control.safe.drive
 ***                rNeutral                                        
 *** Ca4            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerneutral                       
 *** Ca5            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown                          
 *** Ca6            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.iniPassengerDown         
 *** Ca7            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.passengerDown            
 *** Ca8            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.autoPassengerDown        
 *** Ca9            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp                            
 *** Ca10           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.iniPassengerUp             
 *** Ca11           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.PassengerUp                
 *** Ca12           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.autoPassengerUp            
 *** Ca13           power_window_controller_ver3/control.safe.drive
 ***                rUp                                             
 *** Ca14           power_window_controller_ver3/control.safe.drive
 ***                rUp.iniDriverUp                                 
 *** Ca15           power_window_controller_ver3/control.safe.drive
 ***                rUp.DriverUp                                    
 *** Ca16           power_window_controller_ver3/control.safe.drive
 ***                rUp.autoDriverUp                                
 *** Ca17           power_window_controller_ver3/control.safe.drive
 ***                rDown                                           
 *** Ca18           power_window_controller_ver3/control.safe.drive
 ***                rDown.iniDriverDown                             
 *** Ca19           power_window_controller_ver3/control.safe.drive
 ***                rDown.DriverDown                                
 *** Ca20           power_window_controller_ver3/control.safe.drive
 ***                rDown.autoDriverDown                            
 *** Ca21           power_window_controller_ver3/control.emergencyD
 ***                own                                             
 *** 
 *** TargetLink version      : 22.1 from 02-Nov-2022
 *** Code generator version  : Build Id 22.1.0.27 from 2022-10-13 12:48:15
\**************************************************************************************************/

#ifndef POWER_WINDOW_CONTROLLER_VER3_C
#define POWER_WINDOW_CONTROLLER_VER3_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "validate_passenger.h"
#include "validate_driver.h"
#include "power_window_controller_ver3.h"
#include "detect_obstacle_endstop.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   CAL: global calibratable parameters (ROM) | Width: 8
\**************************************************************************************************/
CAL UInt8 Sa1_auto_down_time = 100; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255
   Description: value in 10 ms steps */
CAL UInt8 Sa1_auto_up_time = 100; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255
   Description: value in 10 ms steps */
CAL UInt8 Sa1_emergency_down_time = 100; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255
   Description: value in 10 ms steps */

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 16
\**************************************************************************************************/
GLOBAL UInt16 Sa1_obstacle_position; /* 
   LSB: 0.001 OFF: 0 MIN/MAX: 0 .. 0.45
   Description: obstacle position in mm */
GLOBAL UInt16 Sa1_window_position; /* 
   LSB: 0.001 OFF: 0 MIN/MAX: 0 .. 0.45
   Description: window position in mm */

/**************************************************************************************************\
   GLOBAL: global variables (RAM) | Width: 8
\**************************************************************************************************/
GLOBAL Bool Sa1_driver_down;
GLOBAL Bool Sa1_driver_up;
GLOBAL Bool Sa1_move_down;
GLOBAL Bool Sa1_move_up;
GLOBAL Bool Sa1_obstacle_detection;
GLOBAL Bool Sa1_passenger_down;
GLOBAL Bool Sa1_passenger_up;

/**************************************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    8
\**************************************************************************************************/
static Bool Ca1_moveDown = 0;
static Bool Ca1_moveUp = 0;

/**************************************************************************************************\
   SFStaticGlobalInit: Default storage class for global static variables with initial value | Width:
    N.A.
\**************************************************************************************************/
static struct tag_SIBFS_control_a_tp SIBFS_control_a = {
   0, /* Ca10_iniPassengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca11_PassengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca13_driverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca14_iniDriverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca15_DriverUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca17_driverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca18_iniDriverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca19_DriverDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca21_emergencyDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca2_safe: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca3_driverNeutral: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca4_passengerneutral: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca5_passengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca6_iniPassengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0, /* Ca7_passengerDown: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
   0 /* Ca9_passengerUp: LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
}; /* Description: Structure containing bitfields for Stateflow chart  */

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   StaticSFEntry: Default function class for static stateflow entry functions
\**************************************************************************************************/
static void Ca4_passengerneutral_en(void);

/**************************************************************************************************\
   StaticSFExit: Default function class for static stateflow exit functions
\**************************************************************************************************/
static void Ca3_driverNeutral_ex(void);
static void Ca5_passengerDown_ex(void);
static void Ca9_passengerUp_ex(void);

/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      power_window_controller_ver3
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void power_window_controller_ver3(void)
{
   /* SFStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static UInt8 Ca1_control_ctr = 0;
   static UInt8 Ca1_control_ctr_a = 0;
   static UInt8 Ca1_control_ctr_b = 0;

   /* SLStaticLocalInit: Default storage class for static local variables with initvalue | Width: 8
   */
   static Bool X_Sa1_Unit_Delay = 0;

   /* call of function: power_window_controller_ver3/detect_obstacle_endstop
      # combined # update(s) for inport power_window_controller_ver3/detect_obstacle_endstop/window_
      position */
   detect_obstacle_endstop(Sa1_obstacle_position, (UInt8) Sa1_window_position, X_Sa1_Unit_Delay);

   /* call of function: power_window_controller_ver3/validate_driver
      TL_AUTO_COMMENT BLOCKREF ('validate_driver', 'power_window_controller_ver3/validate_driver/Fun
      ction', ()) */
   validate_driver();

   /* call of function: power_window_controller_ver3/validate_passenger
      TL_AUTO_COMMENT BLOCKREF ('validate_passenger', 'power_window_controller_ver3/validate_passeng
      er/Function', ()) */
   validate_passenger();

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('<', 'power_window_c
      ontroller_ver3/control', ('power_window_controller_ver3/control', 'power_window_controller_ver
      3/control')))) */
   if (Ca1_control_ctr < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', ('+', 'power_window_controller_ver3/control', ('power_window_controlle
         r_ver3/control', 'power_window_controller_ver3/control')))) */
      Ca1_control_ctr = Ca1_control_ctr + 1;
   }

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('<', 'power_window_c
      ontroller_ver3/control', ('power_window_controller_ver3/control', 'power_window_controller_ver
      3/control')))) */
   if (Ca1_control_ctr_a < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', ('+', 'power_window_controller_ver3/control', ('power_window_controlle
         r_ver3/control', 'power_window_controller_ver3/control')))) */
      Ca1_control_ctr_a = Ca1_control_ctr_a + 1;
   }

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('<', 'power_window_c
      ontroller_ver3/control', ('power_window_controller_ver3/control', 'power_window_controller_ver
      3/control')))) */
   if (Ca1_control_ctr_b < 255) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', ('+', 'power_window_controller_ver3/control', ('power_window_controlle
         r_ver3/control', 'power_window_controller_ver3/control')))) */
      Ca1_control_ctr_b = Ca1_control_ctr_b + 1;
   }

   /* Begin execution of chart power_window_controller_ver3/control */

   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_control
      ler_ver3/control')) */
   if (SIBFS_control_a.Ca2_safe) {
      /* Begin execution of state power_window_controller_ver3/control.safe */
      if (SIBFS_control_a.Ca3_driverNeutral) {
         /* Begin execution of state power_window_controller_ver3/control.safe.driverNeutral */

         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_c
            ontroller_ver3/detect_obstacle_endstop/obstacle')) */
         if (Sa2_obstacle) {
            /* State transition from power_window_controller_ver3/control.safe.driverNeutral to powe
               r_window_controller_ver3/control.emergencyDown */

            /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller_ver3/contr
               ol', ()) */
            Ca3_driverNeutral_ex();

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control', 'power_window_controller_ver3/control')) */
            SIBFS_control_a.Ca2_safe = 0;
            Ca1_control_ctr = 0;
            SIBFS_control_a.Ca21_emergencyDown = 1;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control.moveUp', 'power_window_controller_ver3/control')) */
            Ca1_moveUp = 0;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control.moveDown', 'power_window_controller_ver3/control')) */
            Ca1_moveDown = 1;
         }
         else {
            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_windo
               w_controller_ver3/validate_driver/mutually_exclusive/up_after_down')) */
            if (Sa10_up_after_down) {
               /* State transition from power_window_controller_ver3/control.safe.driverNeutral to p
                  ower_window_controller_ver3/control.safe.driverUp.iniDriverUp */

               /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller_ver3/co
                  ntrol', ()) */
               Ca3_driverNeutral_ex();

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               SIBFS_control_a.Ca13_driverUp = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control.moveUp', 'power_window_controller_ver3/control')) */
               Ca1_moveUp = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               Ca1_control_ctr_b = 0;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               SIBFS_control_a.Ca14_iniDriverUp = 1;
            }
            else {
               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('!=', 'p
                  ower_window_controller_ver3/validate_driver/driver_switch/control input3', ('power
                  _window_controller_ver3/validate_driver/driver_switch/control input3', 'power_wind
                  ow_controller_ver3/validate_driver/driver_switch/control input3')))) */
               if (Sa9_control_input3 != 0) {
                  /* State transition from power_window_controller_ver3/control.safe.driverNeutral t
                     o power_window_controller_ver3/control.safe.driverDown.iniDriverDown */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca3_driverNeutral_ex', 'power_window_controller_ver3
                     /control', ()) */
                  Ca3_driverNeutral_ex();

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca17_driverDown = 1;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control.moveDown', 'power_window_controller_ver3/control
                     ')) */
                  Ca1_moveDown = 1;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  Ca1_control_ctr_b = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca18_iniDriverDown = 1;
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/control')) */
                  if (SIBFS_control_a.Ca4_passengerneutral) {
                     /* Begin execution of state power_window_controller_ver3/control.safe.driverNeu
                        tral.passengerneutral */

                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/validate_passenger/mutually_exclusive/up_after_do
                        wn')) */
                     if (Sa13_up_after_down) {
                        /* State transition from power_window_controller_ver3/control.safe.driverNeu
                           tral.passengerneutral to power_window_controller_ver3/control.safe.driver
                           Neutral.passengerUp.iniPassengerUp */

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca4_passengerneutral = 0;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca9_passengerUp = 1;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control.moveUp', 'power_window_controller_ve
                           r3/control')) */
                        Ca1_moveUp = 1;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        Ca1_control_ctr_a = 0;

                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca10_iniPassengerUp = 1;
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/validate_passenger/check_down/allow_action'
                           )) */
                        if (Sa11_allow_action) {
                           /* State transition from power_window_controller_ver3/control.safe.driver
                              Neutral.passengerneutral to power_window_controller_ver3/control.safe.
                              driverNeutral.passengerDown.iniPassengerDown */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca4_passengerneutral = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca5_passengerDown = 1;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control.moveDown', 'power_window_contr
                              oller_ver3/control')) */
                           Ca1_moveDown = 1;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           Ca1_control_ctr_a = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca6_iniPassengerDown = 1;
                        }
                     }
                     /* End execution of state power_window_controller_ver3/control.safe.driverNeutr
                        al.passengerneutral */
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca5_passengerDown) {
                        /* Begin execution of state power_window_controller_ver3/control.safe.driver
                           Neutral.passengerDown */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/detect_obstacle_endstop/endstop_bottom'))
                           */
                        if (Sa2_endstop_bottom) {
                           /* State transition from power_window_controller_ver3/control.safe.driver
                              Neutral.passengerDown to power_window_controller_ver3/control.safe.dri
                              verNeutral.passengerneutral */

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_contro
                              ller_ver3/control', ()) */
                           Ca5_passengerDown_ex();

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_con
                              troller_ver3/control', ()) */
                           Ca4_passengerneutral_en();
                        }
                        else {
                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control'
                              , ('power_window_controller_ver3/validate_passenger/mutually_exclusive
                              /up_after_down')) */
                           if (Sa13_up_after_down) {
                              /* State transition from power_window_controller_ver3/control.safe.dri
                                 verNeutral.passengerDown to power_window_controller_ver3/control.sa
                                 fe.driverNeutral.passengerUp.PassengerUp */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_con
                                 troller_ver3/control', ()) */
                              Ca5_passengerDown_ex();

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca9_passengerUp = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control.moveUp', 'power_window_c
                                 ontroller_ver3/control')) */
                              Ca1_moveUp = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca11_PassengerUp = 1;
                           }
                           else {
                              /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/contr
                                 ol', ('power_window_controller_ver3/control')) */
                              if (SIBFS_control_a.Ca6_iniPassengerDown) {
                                 /* Begin execution of state power_window_controller_ver3/control.sa
                                    fe.driverNeutral.passengerDown.iniPassengerDown */

                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/co
                                    ntrol', (('>=', 'power_window_controller_ver3/control', ('power_
                                    window_controller_ver3/control', 'power_window_controller_ver3/C
                                    onstant1')))) */
                                 if (Ca1_control_ctr_a >= Sa1_auto_down_time) {
                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3
                                       /control', ('power_window_controller_ver3/validate_passenger/
                                       mutually_exclusive/default_neutral')) */
                                    if (Sa13_default_neutral) {
                                       /* State transition to power_window_controller_ver3/control.s
                                          afe.driverNeutral.passengerDown.autoPassengerDown */

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ve
                                          r3/control', ('power_window_controller_ver3/control', 'pow
                                          er_window_controller_ver3/control')) */
                                       SIBFS_control_a.Ca6_iniPassengerDown = 0;
                                    }
                                    else {
                                       /* State transition to power_window_controller_ver3/control.s
                                          afe.driverNeutral.passengerDown.passengerDown */
                                       SIBFS_control_a.Ca6_iniPassengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ve
                                          r3/control', ('power_window_controller_ver3/control', 'pow
                                          er_window_controller_ver3/control')) */
                                       SIBFS_control_a.Ca7_passengerDown = 1;
                                    }
                                 }
                                 /* End execution of state power_window_controller_ver3/control.safe
                                    .driverNeutral.passengerDown.iniPassengerDown */
                              }
                              else {
                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/co
                                    ntrol', ('power_window_controller_ver3/control')) */
                                 if (SIBFS_control_a.Ca7_passengerDown) {
                                    /* Begin execution of state power_window_controller_ver3/control
                                       .safe.driverNeutral.passengerDown.passengerDown */

                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3
                                       /control', ('power_window_controller_ver3/validate_passenger/
                                       mutually_exclusive/default_neutral')) */
                                    if (Sa13_default_neutral) {
                                       /* State transition from power_window_controller_ver3/control
                                          .safe.driverNeutral.passengerDown.passengerDown to power_w
                                          indow_controller_ver3/control.safe.driverNeutral.passenger
                                          neutral */

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ve
                                          r3/control', ('power_window_controller_ver3/control', 'pow
                                          er_window_controller_ver3/control')) */
                                       SIBFS_control_a.Ca7_passengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ve
                                          r3/control', ('power_window_controller_ver3/control.moveDo
                                          wn', 'power_window_controller_ver3/control')) */
                                       Ca1_moveDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ve
                                          r3/control', ('power_window_controller_ver3/control', 'pow
                                          er_window_controller_ver3/control')) */
                                       SIBFS_control_a.Ca5_passengerDown = 0;

                                       /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'powe
                                          r_window_controller_ver3/control', ()) */
                                       Ca4_passengerneutral_en();
                                    }
                                    /* End execution of state power_window_controller_ver3/control.s
                                       afe.driverNeutral.passengerDown.passengerDown */
                                 }
                              }
                           }
                        }
                        /* End execution of state power_window_controller_ver3/control.safe.driverNe
                           utral.passengerDown */
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/control')) */
                        if (SIBFS_control_a.Ca9_passengerUp) {
                           /* Begin execution of state power_window_controller_ver3/control.safe.dri
                              verNeutral.passengerUp */

                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control'
                              , ('power_window_controller_ver3/validate_passenger/check_down/allow_a
                              ction')) */
                           if (Sa11_allow_action) {
                              /* State transition from power_window_controller_ver3/control.safe.dri
                                 verNeutral.passengerUp to power_window_controller_ver3/control.safe
                                 .driverNeutral.passengerDown.passengerDown */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_contr
                                 oller_ver3/control', ()) */
                              Ca9_passengerUp_ex();

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca5_passengerDown = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control.moveDown', 'power_window
                                 _controller_ver3/control')) */
                              Ca1_moveDown = 1;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca7_passengerDown = 1;
                           }
                           else {
                              /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/contr
                                 ol', ('power_window_controller_ver3/detect_obstacle_endstop/endstop
                                 _top')) */
                              if (Sa2_endstop_top) {
                                 /* State transition from power_window_controller_ver3/control.safe.
                                    driverNeutral.passengerUp to power_window_controller_ver3/contro
                                    l.safe.driverNeutral.passengerneutral */

                                 /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_co
                                    ntroller_ver3/control', ()) */
                                 Ca9_passengerUp_ex();

                                 /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_wind
                                    ow_controller_ver3/control', ()) */
                                 Ca4_passengerneutral_en();
                              }
                              else {
                                 /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/co
                                    ntrol', ('power_window_controller_ver3/control')) */
                                 if (SIBFS_control_a.Ca10_iniPassengerUp) {
                                    /* Begin execution of state power_window_controller_ver3/control
                                       .safe.driverNeutral.passengerUp.iniPassengerUp */

                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3
                                       /control', (('>=', 'power_window_controller_ver3/control', ('
                                       power_window_controller_ver3/control', 'power_window_controll
                                       er_ver3/Constant2')))) */
                                    if (Ca1_control_ctr_a >= Sa1_auto_up_time) {
                                       /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_v
                                          er3/control', ('power_window_controller_ver3/validate_pass
                                          enger/mutually_exclusive/default_neutral')) */
                                       if (Sa13_default_neutral) {
                                          /* State transition to power_window_controller_ver3/contro
                                          l.safe.driverNeutral.passengerUp.autoPassengerUp */

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          _ver3/control', ('power_window_controller_ver3/control'
                                          , 'power_window_controller_ver3/control')) */
                                          SIBFS_control_a.Ca10_iniPassengerUp = 0;
                                       }
                                       else {
                                          /* State transition to power_window_controller_ver3/contro
                                          l.safe.driverNeutral.passengerUp.PassengerUp */
                                          SIBFS_control_a.Ca10_iniPassengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          _ver3/control', ('power_window_controller_ver3/control'
                                          , 'power_window_controller_ver3/control')) */
                                          SIBFS_control_a.Ca11_PassengerUp = 1;
                                       }
                                    }
                                    /* End execution of state power_window_controller_ver3/control.s
                                       afe.driverNeutral.passengerUp.iniPassengerUp */
                                 }
                                 else {
                                    /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3
                                       /control', ('power_window_controller_ver3/control')) */
                                    if (SIBFS_control_a.Ca11_PassengerUp) {
                                       /* Begin execution of state power_window_controller_ver3/cont
                                          rol.safe.driverNeutral.passengerUp.PassengerUp */

                                       /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_v
                                          er3/control', ('power_window_controller_ver3/validate_pass
                                          enger/mutually_exclusive/default_neutral')) */
                                       if (Sa13_default_neutral) {
                                          /* State transition from power_window_controller_ver3/cont
                                          rol.safe.driverNeutral.passengerUp.PassengerUp to power
                                          _window_controller_ver3/control.safe.driverNeutral.pass
                                          engerneutral */

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          _ver3/control', ('power_window_controller_ver3/control'
                                          , 'power_window_controller_ver3/control')) */
                                          SIBFS_control_a.Ca11_PassengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          _ver3/control', ('power_window_controller_ver3/control.
                                          moveUp', 'power_window_controller_ver3/control')) */
                                          Ca1_moveUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller
                                          _ver3/control', ('power_window_controller_ver3/control'
                                          , 'power_window_controller_ver3/control')) */
                                          SIBFS_control_a.Ca9_passengerUp = 0;

                                          /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'p
                                          ower_window_controller_ver3/control', ()) */
                                          Ca4_passengerneutral_en();
                                       }
                                       /* End execution of state power_window_controller_ver3/contro
                                          l.safe.driverNeutral.passengerUp.PassengerUp */
                                    }
                                 }
                              }
                           }
                           /* End execution of state power_window_controller_ver3/control.safe.drive
                              rNeutral.passengerUp */
                        }
                     }
                  }
               }
            }
         }
         /* End execution of state power_window_controller_ver3/control.safe.driverNeutral */
      }
      else {
         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_c
            ontroller_ver3/control')) */
         if (SIBFS_control_a.Ca13_driverUp) {
            /* Begin execution of state power_window_controller_ver3/control.safe.driverUp */

            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('!=', 'powe
               r_window_controller_ver3/validate_driver/driver_switch/control input3', ('power_windo
               w_controller_ver3/validate_driver/driver_switch/control input3', 'power_window_contro
               ller_ver3/validate_driver/driver_switch/control input3')))) */
            if (Sa9_control_input3 != 0) {
               /* State transition from power_window_controller_ver3/control.safe.driverUp to power_
                  window_controller_ver3/control.safe.driverDown.DriverDown */
               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_wi
                  ndow_controller_ver3/control')) */
               if (SIBFS_control_a.Ca14_iniDriverUp) {
                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca14_iniDriverUp = 0;
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/control')) */
                  if (SIBFS_control_a.Ca15_DriverUp) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca15_DriverUp = 0;
                  }
               }

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control.moveUp', 'power_window_controller_ver3/control')) */
               Ca1_moveUp = 0;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               SIBFS_control_a.Ca13_driverUp = 0;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               SIBFS_control_a.Ca17_driverDown = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control.moveDown', 'power_window_controller_ver3/control')) */
               Ca1_moveDown = 1;

               /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_win
                  dow_controller_ver3/control', 'power_window_controller_ver3/control')) */
               SIBFS_control_a.Ca19_DriverDown = 1;
            }
            else {
               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_wi
                  ndow_controller_ver3/detect_obstacle_endstop/endstop_top')) */
               if (Sa2_endstop_top) {
                  /* State transition from power_window_controller_ver3/control.safe.driverUp to pow
                     er_window_controller_ver3/control.safe.driverNeutral */
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/control')) */
                  if (SIBFS_control_a.Ca14_iniDriverUp) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca14_iniDriverUp = 0;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca15_DriverUp) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca15_DriverUp = 0;
                     }
                  }

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control.moveUp', 'power_window_controller_ver3/control')
                     ) */
                  Ca1_moveUp = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca13_driverUp = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca3_driverNeutral = 1;

                  /* State transition to power_window_controller_ver3/control.safe.driverNeutral.pas
                     sengerneutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller_v
                     er3/control', ()) */
                  Ca4_passengerneutral_en();
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/control')) */
                  if (SIBFS_control_a.Ca14_iniDriverUp) {
                     /* Begin execution of state power_window_controller_ver3/control.safe.driverUp.
                        iniDriverUp */

                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('>
                        =', 'power_window_controller_ver3/control', ('power_window_controller_ver3/c
                        ontrol', 'power_window_controller_ver3/Constant2')))) */
                     if (Ca1_control_ctr_b >= Sa1_auto_up_time) {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/validate_driver/mutually_exclusive/default_
                           neutral')) */
                        if (Sa10_default_neutral) {
                           /* State transition to power_window_controller_ver3/control.safe.driverUp
                              .autoDriverUp */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca14_iniDriverUp = 0;
                        }
                        else {
                           /* State transition to power_window_controller_ver3/control.safe.driverUp
                              .DriverUp */
                           SIBFS_control_a.Ca14_iniDriverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca15_DriverUp = 1;
                        }
                     }
                     /* End execution of state power_window_controller_ver3/control.safe.driverUp.in
                        iDriverUp */
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca15_DriverUp) {
                        /* Begin execution of state power_window_controller_ver3/control.safe.driver
                           Up.DriverUp */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/validate_driver/mutually_exclusive/default_
                           neutral')) */
                        if (Sa10_default_neutral) {
                           /* State transition from power_window_controller_ver3/control.safe.driver
                              Up.DriverUp to power_window_controller_ver3/control.safe.driverNeutral
                               */

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca15_DriverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control.moveUp', 'power_window_control
                              ler_ver3/control')) */
                           Ca1_moveUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca13_driverUp = 0;

                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca3_driverNeutral = 1;

                           /* State transition to power_window_controller_ver3/control.safe.driverNe
                              utral.passengerneutral */

                           /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_con
                              troller_ver3/control', ()) */
                           Ca4_passengerneutral_en();
                        }
                        /* End execution of state power_window_controller_ver3/control.safe.driverUp
                           .DriverUp */
                     }
                  }
               }
            }
            /* End execution of state power_window_controller_ver3/control.safe.driverUp */
         }
         else {
            /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_windo
               w_controller_ver3/control')) */
            if (SIBFS_control_a.Ca17_driverDown) {
               /* Begin execution of state power_window_controller_ver3/control.safe.driverDown */

               /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_wi
                  ndow_controller_ver3/detect_obstacle_endstop/endstop_bottom')) */
               if (Sa2_endstop_bottom) {
                  /* State transition from power_window_controller_ver3/control.safe.driverDown to p
                     ower_window_controller_ver3/control.safe.driverNeutral */
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/control')) */
                  if (SIBFS_control_a.Ca18_iniDriverDown) {
                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca18_iniDriverDown = 0;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca19_DriverDown) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca19_DriverDown = 0;
                     }
                  }

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control.moveDown', 'power_window_controller_ver3/control
                     ')) */
                  Ca1_moveDown = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca17_driverDown = 0;

                  /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_
                     window_controller_ver3/control', 'power_window_controller_ver3/control')) */
                  SIBFS_control_a.Ca3_driverNeutral = 1;

                  /* State transition to power_window_controller_ver3/control.safe.driverNeutral.pas
                     sengerneutral */

                  /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller_v
                     er3/control', ()) */
                  Ca4_passengerneutral_en();
               }
               else {
                  /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power
                     _window_controller_ver3/validate_driver/mutually_exclusive/up_after_down')) */
                  if (Sa10_up_after_down) {
                     /* State transition from power_window_controller_ver3/control.safe.driverDown t
                        o power_window_controller_ver3/control.safe.driverUp.DriverUp */
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca18_iniDriverDown) {
                        /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('
                           power_window_controller_ver3/control', 'power_window_controller_ver3/cont
                           rol')) */
                        SIBFS_control_a.Ca18_iniDriverDown = 0;
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/control')) */
                        if (SIBFS_control_a.Ca19_DriverDown) {
                           /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control',
                               ('power_window_controller_ver3/control', 'power_window_controller_ver
                              3/control')) */
                           SIBFS_control_a.Ca19_DriverDown = 0;
                        }
                     }

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control.moveDown', 'power_window_controller_ver3/c
                        ontrol')) */
                     Ca1_moveDown = 0;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca17_driverDown = 0;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca13_driverUp = 1;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control.moveUp', 'power_window_controller_ver3/con
                        trol')) */
                     Ca1_moveUp = 1;

                     /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('pow
                        er_window_controller_ver3/control', 'power_window_controller_ver3/control'))
                         */
                     SIBFS_control_a.Ca15_DriverUp = 1;
                  }
                  else {
                     /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('po
                        wer_window_controller_ver3/control')) */
                     if (SIBFS_control_a.Ca18_iniDriverDown) {
                        /* Begin execution of state power_window_controller_ver3/control.safe.driver
                           Down.iniDriverDown */

                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           ('>=', 'power_window_controller_ver3/control', ('power_window_controller_
                           ver3/control', 'power_window_controller_ver3/Constant1')))) */
                        if (Ca1_control_ctr_b >= Sa1_auto_down_time) {
                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control'
                              , ('power_window_controller_ver3/validate_driver/mutually_exclusive/de
                              fault_neutral')) */
                           if (Sa10_default_neutral) {
                              /* State transition to power_window_controller_ver3/control.safe.drive
                                 rDown.autoDriverDown */

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca18_iniDriverDown = 0;
                           }
                           else {
                              /* State transition to power_window_controller_ver3/control.safe.drive
                                 rDown.DriverDown */
                              SIBFS_control_a.Ca18_iniDriverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca19_DriverDown = 1;
                           }
                        }
                        /* End execution of state power_window_controller_ver3/control.safe.driverDo
                           wn.iniDriverDown */
                     }
                     else {
                        /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (
                           'power_window_controller_ver3/control')) */
                        if (SIBFS_control_a.Ca19_DriverDown) {
                           /* Begin execution of state power_window_controller_ver3/control.safe.dri
                              verDown.DriverDown */

                           /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control'
                              , ('power_window_controller_ver3/validate_driver/mutually_exclusive/de
                              fault_neutral')) */
                           if (Sa10_default_neutral) {
                              /* State transition from power_window_controller_ver3/control.safe.dri
                                 verDown.DriverDown to power_window_controller_ver3/control.safe.dri
                                 verNeutral */

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca19_DriverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control.moveDown', 'power_window
                                 _controller_ver3/control')) */
                              Ca1_moveDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca17_driverDown = 0;

                              /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/contro
                                 l', ('power_window_controller_ver3/control', 'power_window_controll
                                 er_ver3/control')) */
                              SIBFS_control_a.Ca3_driverNeutral = 1;

                              /* State transition to power_window_controller_ver3/control.safe.drive
                                 rNeutral.passengerneutral */

                              /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_
                                 controller_ver3/control', ()) */
                              Ca4_passengerneutral_en();
                           }
                           /* End execution of state power_window_controller_ver3/control.safe.drive
                              rDown.DriverDown */
                        }
                     }
                  }
               }
               /* End execution of state power_window_controller_ver3/control.safe.driverDown */
            }
         }
      }
      /* End execution of state power_window_controller_ver3/control.safe */
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_cont
         roller_ver3/control')) */
      if (SIBFS_control_a.Ca21_emergencyDown) {
         /* Begin execution of state power_window_controller_ver3/control.emergencyDown */

         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', (('||', 'power_w
            indow_controller_ver3/control', ('power_window_controller_ver3/detect_obstacle_endstop/e
            ndstop_bottom', ('>=', 'power_window_controller_ver3/control', ('power_window_controller
            _ver3/control', 'power_window_controller_ver3/Constant')))))) */
         if (Sa2_endstop_bottom || (Ca1_control_ctr >= Sa1_emergency_down_time)) {
            /* State transition from power_window_controller_ver3/control.emergencyDown to power_win
               dow_controller_ver3/control.safe.driverNeutral.passengerneutral */

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control', 'power_window_controller_ver3/control')) */
            SIBFS_control_a.Ca21_emergencyDown = 0;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control', 'power_window_controller_ver3/control')) */
            SIBFS_control_a.Ca2_safe = 1;

            /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window
               _controller_ver3/control', 'power_window_controller_ver3/control')) */
            SIBFS_control_a.Ca3_driverNeutral = 1;

            /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller_ver3/co
               ntrol', ()) */
            Ca4_passengerneutral_en();
         }
         /* End execution of state power_window_controller_ver3/control.emergencyDown */
      }
      else {
         /* State transition to power_window_controller_ver3/control.safe */

         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_co
            ntroller_ver3/control', 'power_window_controller_ver3/control')) */
         SIBFS_control_a.Ca2_safe = 1;

         /* State transition to power_window_controller_ver3/control.safe.driverNeutral */
         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_co
            ntroller_ver3/control', 'power_window_controller_ver3/control')) */
         SIBFS_control_a.Ca3_driverNeutral = 1;

         /* State transition to power_window_controller_ver3/control.safe.driverNeutral.passengerneu
            tral */

         /* TL_AUTO_COMMENT BLOCKREF ('Ca4_passengerneutral_en', 'power_window_controller_ver3/contr
            ol', ()) */
         Ca4_passengerneutral_en();
      }
   }
   /* End execution of chart power_window_controller_ver3/control */

   /* Unit delay: power_window_controller_ver3/Unit Delay
      TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/Unit Delay', ('power_window_contr
      oller_ver3/Unit Delay', 'power_window_controller_ver3/control.moveUp')) */
   X_Sa1_Unit_Delay = Ca1_moveUp;

   /* TargetLink outport: power_window_controller_ver3/move_down
      TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/move_down', ('power_window_contro
      ller_ver3/move_down', 'power_window_controller_ver3/control.moveDown')) */
   Sa1_move_down = Ca1_moveDown;

   /* TargetLink outport: power_window_controller_ver3/move_up
      TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/move_up', ('power_window_controll
      er_ver3/move_up', 'power_window_controller_ver3/control.moveUp')) */
   Sa1_move_up = Ca1_moveUp;

   /* TargetLink outport: power_window_controller_ver3/obstacle_detection
      TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/obstacle_detection', ('power_wind
      ow_controller_ver3/obstacle_detection', 'power_window_controller_ver3/detect_obstacle_endstop/
      obstacle')) */
   Sa1_obstacle_detection = Sa2_obstacle;
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca4_passengerneutral_en
 *** 
 ***  DESCRIPTION:
 ***      Entry function of state: power_window_controller_ver3/control.safe.driverNeutral.passenger
 ***      neutral
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca4_passengerneutral_en(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control', 'power_window_controller_ver3/control')) */
   SIBFS_control_a.Ca4_passengerneutral = 1;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control.moveUp', 'power_window_controller_ver3/control')) */
   Ca1_moveUp = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control.moveDown', 'power_window_controller_ver3/control')) */
   Ca1_moveDown = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca3_driverNeutral_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller_ver3/control.safe.driverNeutral
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca3_driverNeutral_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_control
      ler_ver3/control')) */
   if (SIBFS_control_a.Ca4_passengerneutral) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', 'power_window_controller_ver3/control')) */
      SIBFS_control_a.Ca4_passengerneutral = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_cont
         roller_ver3/control')) */
      if (SIBFS_control_a.Ca5_passengerDown) {
         /* TL_AUTO_COMMENT BLOCKREF ('Ca5_passengerDown_ex', 'power_window_controller_ver3/control'
            , ()) */
         Ca5_passengerDown_ex();
      }
      else {
         /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_c
            ontroller_ver3/control')) */
         if (SIBFS_control_a.Ca9_passengerUp) {
            /* TL_AUTO_COMMENT BLOCKREF ('Ca9_passengerUp_ex', 'power_window_controller_ver3/control
               ', ()) */
            Ca9_passengerUp_ex();
         }
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control', 'power_window_controller_ver3/control')) */
   SIBFS_control_a.Ca3_driverNeutral = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca5_passengerDown_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller_ver3/control.safe.driverNeutral.passengerD
 ***      own
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca5_passengerDown_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_control
      ler_ver3/control')) */
   if (SIBFS_control_a.Ca6_iniPassengerDown) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', 'power_window_controller_ver3/control')) */
      SIBFS_control_a.Ca6_iniPassengerDown = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_cont
         roller_ver3/control')) */
      if (SIBFS_control_a.Ca7_passengerDown) {
         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_co
            ntroller_ver3/control', 'power_window_controller_ver3/control')) */
         SIBFS_control_a.Ca7_passengerDown = 0;
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control.moveDown', 'power_window_controller_ver3/control')) */
   Ca1_moveDown = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control', 'power_window_controller_ver3/control')) */
   SIBFS_control_a.Ca5_passengerDown = 0;
}

/**************************************************************************************************\
 ***  FUNCTION:
 ***      Ca9_passengerUp_ex
 *** 
 ***  DESCRIPTION:
 ***      Exit function of state: power_window_controller_ver3/control.safe.driverNeutral.passengerU
 ***      p
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
static void Ca9_passengerUp_ex(void)
{
   /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_control
      ler_ver3/control')) */
   if (SIBFS_control_a.Ca10_iniPassengerUp) {
      /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_contr
         oller_ver3/control', 'power_window_controller_ver3/control')) */
      SIBFS_control_a.Ca10_iniPassengerUp = 0;
   }
   else {
      /* TL_AUTO_COMMENT BLOCKREF ('if', 'power_window_controller_ver3/control', ('power_window_cont
         roller_ver3/control')) */
      if (SIBFS_control_a.Ca11_PassengerUp) {
         /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_co
            ntroller_ver3/control', 'power_window_controller_ver3/control')) */
         SIBFS_control_a.Ca11_PassengerUp = 0;
      }
   }

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control.moveUp', 'power_window_controller_ver3/control')) */
   Ca1_moveUp = 0;

   /* TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/control', ('power_window_controll
      er_ver3/control', 'power_window_controller_ver3/control')) */
   SIBFS_control_a.Ca9_passengerUp = 0;
}

#ifdef __cplusplus
}
#endif

#endif /* POWER_WINDOW_CONTROLLER_VER3_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
