/**************************************************************************************************\
 *** 
 *** Simulink model       : test
 *** TargetLink subsystem : test/power_window_controller_ver3
 *** Codefile             : validate_passenger.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2025-02-19 01:23:33
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            power_window_controller_ver3
 *** Sa2            power_window_controller_ver3/detect_obstacle_endstop
 *** Sa3            power_window_controller_ver3/validate_driver
 *** Sa4            power_window_controller_ver3/validate_passenger
 *** Sa5            power_window_controller_ver3/detect_obstacle_endstop/detect_endstop
 *** Sa6            power_window_controller_ver3/detect_obstacle_endstop/detect_obstacle
 *** Sa7            power_window_controller_ver3/validate_driver/check_down
 *** Sa8            power_window_controller_ver3/validate_driver/check_up
 *** Sa9            power_window_controller_ver3/validate_driver/driver_switch
 *** Sa10           power_window_controller_ver3/validate_driver/mutually_exclusive
 *** Sa11           power_window_controller_ver3/validate_passenger/check_down
 *** Sa12           power_window_controller_ver3/validate_passenger/check_up
 *** Sa13           power_window_controller_ver3/validate_passenger/mutually_exclusive
 *** Sa14           power_window_controller_ver3/validate_passenger/passenger_switch
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** Ca0            test                                            
 *** Ca1            power_window_controller_ver3/control            
 *** Ca2            power_window_controller_ver3/control.safe       
 *** Ca3            power_window_controller_ver3/control.safe.drive
 ***                rNeutral                                        
 *** Ca4            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerneutral                       
 *** Ca5            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown                          
 *** Ca6            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.iniPassengerDown         
 *** Ca7            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.passengerDown            
 *** Ca8            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.autoPassengerDown        
 *** Ca9            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp                            
 *** Ca10           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.iniPassengerUp             
 *** Ca11           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.PassengerUp                
 *** Ca12           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.autoPassengerUp            
 *** Ca13           power_window_controller_ver3/control.safe.drive
 ***                rUp                                             
 *** Ca14           power_window_controller_ver3/control.safe.drive
 ***                rUp.iniDriverUp                                 
 *** Ca15           power_window_controller_ver3/control.safe.drive
 ***                rUp.DriverUp                                    
 *** Ca16           power_window_controller_ver3/control.safe.drive
 ***                rUp.autoDriverUp                                
 *** Ca17           power_window_controller_ver3/control.safe.drive
 ***                rDown                                           
 *** Ca18           power_window_controller_ver3/control.safe.drive
 ***                rDown.iniDriverDown                             
 *** Ca19           power_window_controller_ver3/control.safe.drive
 ***                rDown.DriverDown                                
 *** Ca20           power_window_controller_ver3/control.safe.drive
 ***                rDown.autoDriverDown                            
 *** Ca21           power_window_controller_ver3/control.emergencyD
 ***                own                                             
 *** 
 *** TargetLink version      : 22.1 from 02-Nov-2022
 *** Code generator version  : Build Id 22.1.0.27 from 2022-10-13 12:48:15
\**************************************************************************************************/

#ifndef VALIDATE_PASSENGER_C
#define VALIDATE_PASSENGER_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "validate_passenger.h"
#include "power_window_controller_ver3.h"
#include "detect_obstacle_endstop.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
Bool Sa11_allow_action;
Bool Sa13_default_neutral;
Bool Sa13_up_after_down;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      validate_passenger
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void validate_passenger(void)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   Bool Sa12_allow_action;

   /* Logical: power_window_controller_ver3/validate_passenger/check_down/allow_action
      # combined # Logical: power_window_controller_ver3/validate_passenger/check_down/not
      # combined # Rescaler: power_window_controller_ver3/validate_passenger/passenger_switch/contro
      l input3 */
   Sa11_allow_action = Sa1_passenger_down && (!(Sa2_endstop_bottom));

   /* Logical: power_window_controller_ver3/validate_passenger/check_up/allow_action
      # combined # Logical: power_window_controller_ver3/validate_passenger/check_up/not
      # combined # Rescaler: power_window_controller_ver3/validate_passenger/passenger_switch/contro
      l input2 */
   Sa12_allow_action = Sa1_passenger_up && (!(Sa2_endstop_top));

   /* Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/up_after_down
      # combined # Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/not_d
      own */
   Sa13_up_after_down = Sa12_allow_action && (!(Sa11_allow_action));

   /* Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/default_neutral
      # combined # Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/not_u
      p1
      # combined # Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/neutr
      al_after_up
      # combined # Logical: power_window_controller_ver3/validate_passenger/mutually_exclusive/not_u
      p
      # combined # Logical: power_window_controller_ver3/validate_passenger/passenger_switch/Logical
       Operator1 */
   Sa13_default_neutral = ((!(Sa1_passenger_up)) && (!(Sa1_passenger_down)) &&
    (!(Sa13_up_after_down))) || ((!(Sa12_allow_action)) && (!(Sa11_allow_action)));
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* VALIDATE_PASSENGER_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
