/**************************************************************************************************\
 *** 
 *** Simulink model       : test
 *** TargetLink subsystem : test/power_window_controller_ver3
 *** Codefile             : validate_driver.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2025-02-19 01:23:33
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Utilize bitwise shift operations         : AvoidPotentiallyUndefinedShiftsBasedOnSignedness
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 2022-B\Matlab\Tl\
 ***                                            XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** SUBSYS         CORRESPONDING SIMULINK SUBSYSTEM
 *** Sa1            power_window_controller_ver3
 *** Sa2            power_window_controller_ver3/detect_obstacle_endstop
 *** Sa3            power_window_controller_ver3/validate_driver
 *** Sa4            power_window_controller_ver3/validate_passenger
 *** Sa5            power_window_controller_ver3/detect_obstacle_endstop/detect_endstop
 *** Sa6            power_window_controller_ver3/detect_obstacle_endstop/detect_obstacle
 *** Sa7            power_window_controller_ver3/validate_driver/check_down
 *** Sa8            power_window_controller_ver3/validate_driver/check_up
 *** Sa9            power_window_controller_ver3/validate_driver/driver_switch
 *** Sa10           power_window_controller_ver3/validate_driver/mutually_exclusive
 *** Sa11           power_window_controller_ver3/validate_passenger/check_down
 *** Sa12           power_window_controller_ver3/validate_passenger/check_up
 *** Sa13           power_window_controller_ver3/validate_passenger/mutually_exclusive
 *** Sa14           power_window_controller_ver3/validate_passenger/passenger_switch
 *** 
 *** SUBSYS         CORRESPONDING MODEL BLOCK (REFERENCED MODEL)
 *** 
 *** SF-NODE        CORRESPONDING STATEFLOW NODE                    DESCRIPTION
 *** Ca0            test                                            
 *** Ca1            power_window_controller_ver3/control            
 *** Ca2            power_window_controller_ver3/control.safe       
 *** Ca3            power_window_controller_ver3/control.safe.drive
 ***                rNeutral                                        
 *** Ca4            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerneutral                       
 *** Ca5            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown                          
 *** Ca6            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.iniPassengerDown         
 *** Ca7            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.passengerDown            
 *** Ca8            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerDown.autoPassengerDown        
 *** Ca9            power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp                            
 *** Ca10           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.iniPassengerUp             
 *** Ca11           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.PassengerUp                
 *** Ca12           power_window_controller_ver3/control.safe.drive
 ***                rNeutral.passengerUp.autoPassengerUp            
 *** Ca13           power_window_controller_ver3/control.safe.drive
 ***                rUp                                             
 *** Ca14           power_window_controller_ver3/control.safe.drive
 ***                rUp.iniDriverUp                                 
 *** Ca15           power_window_controller_ver3/control.safe.drive
 ***                rUp.DriverUp                                    
 *** Ca16           power_window_controller_ver3/control.safe.drive
 ***                rUp.autoDriverUp                                
 *** Ca17           power_window_controller_ver3/control.safe.drive
 ***                rDown                                           
 *** Ca18           power_window_controller_ver3/control.safe.drive
 ***                rDown.iniDriverDown                             
 *** Ca19           power_window_controller_ver3/control.safe.drive
 ***                rDown.DriverDown                                
 *** Ca20           power_window_controller_ver3/control.safe.drive
 ***                rDown.autoDriverDown                            
 *** Ca21           power_window_controller_ver3/control.emergencyD
 ***                own                                             
 *** 
 *** TargetLink version      : 22.1 from 02-Nov-2022
 *** Code generator version  : Build Id 22.1.0.27 from 2022-10-13 12:48:15
\**************************************************************************************************/

#ifndef VALIDATE_DRIVER_C
#define VALIDATE_DRIVER_C

/*------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------*/

#include "validate_driver.h"
#include "power_window_controller_ver3.h"
#include "detect_obstacle_endstop.h"

#ifdef __cplusplus
extern "C" {
#endif

/*------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 16
\**************************************************************************************************/
Int16 Sa9_control_input3;

/**************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: 8
\**************************************************************************************************/
Bool Sa10_default_neutral;
Bool Sa10_up_after_down;

/*------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/

/**************************************************************************************************\
 ***  FUNCTION:
 ***      validate_driver
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\**************************************************************************************************/
void validate_driver(void)
{
   /* SLLocal: Default storage class for local variables | Width: 8 */
   Bool Sa8_allow_action;

   /* Rescaler: power_window_controller_ver3/validate_driver/driver_switch/control input3
      TL_AUTO_COMMENT BLOCKREF ('=', 'power_window_controller_ver3/validate_driver/driver_switch/con
      trol input3', ('power_window_controller_ver3/validate_driver/driver_switch/control input3', ('
      (cast)', 'power_window_controller_ver3/driver_down', ('power_window_controller_ver3/driver_dow
      n')))) */
   Sa9_control_input3 = (Int16) Sa1_driver_down;

   /* Logical: power_window_controller_ver3/validate_driver/check_up/allow_action
      # combined # Logical: power_window_controller_ver3/validate_driver/check_up/not
      # combined # Rescaler: power_window_controller_ver3/validate_driver/driver_switch/control inpu
      t2 */
   Sa8_allow_action = Sa1_driver_up && (!(Sa2_endstop_top));

   /* Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/up_after_down
      # combined # Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/not_down
       */
   Sa10_up_after_down = Sa8_allow_action && (!(Sa9_control_input3 != 0));

   /* Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/default_neutral
      # combined # Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/not_up1
      # combined # Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/neutral_
      after_up
      # combined # Logical: power_window_controller_ver3/validate_driver/mutually_exclusive/not_up
      # combined # Logical: power_window_controller_ver3/validate_driver/driver_switch/Logical Opera
      tor1 */
   Sa10_default_neutral = ((!(Sa1_driver_up)) && (!(Sa9_control_input3 != 0)) &&
    (!(Sa10_up_after_down))) || ((!(Sa8_allow_action)) && (!(Sa9_control_input3 != 0)));
}

/*------------------------------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*------------------------------------------------------------------------------------------------*/
#ifdef __cplusplus
}
#endif

#endif /* VALIDATE_DRIVER_C */
/*------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------*/
